spring.application.name=russian-montparnasse
rss.feed.urls=https://www.service-public.gouv.fr/abonnements/rss/actu-actualites-particuliers.rss, https://www.service-public.fr/abonnements/rss/actu-actu-pro.rss

spring.datasource.url=jdbc:h2:mem:russianmontparnasse
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

news.import.interval=3600000
news.import.initial-delay=3600000

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.channel.id=@russian_montparnasse